version: "3.8"
services:
  app:
    build:
      context: .
    restart: always
    environment:
      DATABASE_URL: postgresql://ikaeve:ikaeve@db:5432/ikaeve
    env_file:
      - .env
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: ikaeve
      POSTGRES_DB: ikaeve
      POSTGRES_PASSWORD: ikaeve
