version: "3.8"
services:
  app:
    container_name: ikaeve_app
    build:
      context: ./app
    ports:
      - "5000:5000"
  api:
    container_name: ikaeve_api
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
