version: "3.8"
services:
  api:
    container_name: ikaeve_api
    build:
      context: ./api
    ports:
      - "5000:5000"
  db:
    container_name: ikaeve_db
    build:
      context: ./mariadb
    ports:
      - "3306:3306"
